use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;
use lc_core::storage::{StorageProvider, StoredCard, DeckInfo, NewDeckData, NewCardEntry};

// ----- Shared model definition (used by push_to_anki) -----

const MODEL_NAME: &str = "Panglot";
const MODEL_CSS: &str = "\
.card { font-family: 'Segoe UI', sans-serif; font-size: 18px; text-align: center; color: #e0e0e0; background-color: #2b2b2b; padding: 20px; }\
.translation { color: #b39ddb; font-size: 16px; margin-bottom: 8px; }\
.cloze-sentence { color: #e0e0e0; font-size: 22px; font-weight: bold; margin: 12px 0; }\
.full-sentence { color: #e0e0e0; font-size: 22px; margin: 12px 0; }\
.hint { color: #ef5350; font-size: 14px; margin-top: 4px; }\
.skill-name { color: #66bb6a; font-weight: bold; font-size: 16px; margin: 8px 0; }\
.ipa { font-family: 'Gentium Plus', 'Charis SIL', serif; color: #bdbdbd; font-size: 16px; margin: 8px 0; }\
.text-prompt { color: #90caf9; font-size: 22px; font-weight: bold; }\
.transcript { color: #e0e0e0; font-size: 18px; margin: 8px 0; }\
.listen-prompt { color: #ffab91; font-size: 20px; font-weight: bold; }\
.explanation { text-align: left; font-size: 14px; margin-top: 12px; padding: 10px; background: #333; border-radius: 6px; }\
.audio { margin: 10px 0; }";

const MODEL_QFMT: &str = "{{Front}}";
const MODEL_AFMT: &str = "{{FrontSide}}\
<hr id=answer>\
{{#SkillName}}<div class=\"skill-name\">{{SkillName}}</div>{{/SkillName}}\
{{#IPA}}<div class=\"ipa\">{{IPA}}</div>{{/IPA}}\
{{Back}}\
<div class=\"audio\">{{Audio}}</div>\
{{#Explanation}}<div class=\"explanation\">{{Explanation}}</div>{{/Explanation}}\
<div style=\"display:none\">{{Metadata}}</div>";

const MODEL_FIELDS: &[&str] = &["Front", "Back", "SkillName", "IPA", "Audio", "Explanation", "Metadata"];

// ----- AnkiConnect Implementation -----

/// Storage backend implementation using AnkiConnect.
pub struct AnkiStorageProvider {
    url: String,
    client: reqwest::Client,
}

impl AnkiStorageProvider {
    pub fn new(url: impl Into<String>) -> Self {
        Self {
            url: url.into(),
            client: reqwest::Client::new(),
        }
    }

    async fn invoke(&self, action: &str, params: serde_json::Value) -> Result<serde_json::Value, Box<dyn std::error::Error + Send + Sync>> {
        let payload = serde_json::json!({
            "action": action,
            "version": 6,
            "params": params
        });

        let mut retries = 0;
        let max_retries = 4;
        let mut delay = tokio::time::Duration::from_millis(50);

        loop {
            if retries == 0 {
                tokio::time::sleep(tokio::time::Duration::from_millis(15)).await;
            }

            match self.client.post(&self.url)
                .header("Connection", "close")
                .json(&payload)
                .send()
                .await 
            {
                Ok(resp) => {
                    if !resp.status().is_success() {
                        return Err(format!("AnkiConnect returned HTTP {}", resp.status()).into());
                    }

                    let body: serde_json::Value = resp.json().await?;
                    if let Some(err) = body.get("error") {
                        if !err.is_null() {
                            return Err(format!("AnkiConnect error: {}", err).into());
                        }
                    }

                    return Ok(body["result"].clone());
                }
                Err(e) => {
                    if retries >= max_retries {
                        return Err(Box::new(e));
                    }
                    eprintln!("AnkiConnect network error (retry {}/{} in {}ms): {}", retries + 1, max_retries, delay.as_millis(), e);
                    tokio::time::sleep(delay).await;
                    retries += 1;
                    delay *= 2; // exponential backoff
                }
            }
        }
    }
}

#[async_trait::async_trait]
impl StorageProvider for AnkiStorageProvider {
    async fn fetch_cards(&self) -> Result<Vec<StoredCard>, Box<dyn std::error::Error + Send + Sync>> {
        // Find ONLY cards generated by Panglot
        let find_result = self.invoke("findCards", serde_json::json!({"query": "tag:LC_Version*"})).await?;
        let card_ids: Vec<i64> = serde_json::from_value(find_result)?;

        if card_ids.is_empty() {
            return Ok(vec![]);
        }

        let cards_info_result = self.invoke("cardsInfo", serde_json::json!({"cards": card_ids})).await?;
        let cards_info: Vec<serde_json::Value> = serde_json::from_value(cards_info_result)?;

        let mut raw_cards = Vec::with_capacity(cards_info.len());
        for info in cards_info {
            let card_id = info["cardId"].as_i64().unwrap_or(0);
            let note_id = info["note"].as_i64().unwrap_or(0);
            let interval_days = info["interval"].as_i64().unwrap_or(0) as f64;
            let lapses = info["lapses"].as_i64().unwrap_or(0) as i32;
            
            // Reconstruct fields separated by \x1f (which Analyzer expects)
            let mut fields_string = String::new();
            if let Some(fields_obj) = info["fields"].as_object() {
                let mut ordered_fields = Vec::new();
                for (_k, v) in fields_obj {
                    let order = v["order"].as_i64().unwrap_or(0);
                    let val_str = v["value"].as_str().unwrap_or("");
                    ordered_fields.push((order, val_str));
                }
                ordered_fields.sort_by_key(|a| a.0);

                let vals: Vec<&str> = ordered_fields.into_iter().map(|f| f.1).collect();
                fields_string = vals.join("\x1f");
            }
            
            let tags = if let Some(tags_arr) = info["tags"].as_array() {
                tags_arr.iter().filter_map(|t| t.as_str()).collect::<Vec<_>>().join(" ")
            } else {
                "".to_string()
            };

            raw_cards.push(StoredCard {
                note_id: note_id.to_string(),
                card_id: card_id.to_string(),
                fields: fields_string,
                tags,
                interval_days,
                lapses,
            });
        }

        Ok(raw_cards)
    }

    async fn fetch_decks(&self) -> Result<Vec<DeckInfo>, Box<dyn std::error::Error + Send + Sync>> {
        let deck_names_result = self.invoke("deckNamesAndIds", serde_json::json!({})).await?;
        let deck_map: HashMap<String, i64> = serde_json::from_value(deck_names_result)?;

        let mut decks = Vec::new();
        // Since findCards across many decks individually is slow, we use getDeckStats for total cards
        let stats_result = self.invoke("getDeckStats", serde_json::json!({"decks": deck_map.keys().collect::<Vec<_>>()})).await?;
        let _stats: serde_json::Map<String, serde_json::Value> = serde_json::from_value(stats_result).unwrap_or_default();
        
        for (name, did) in deck_map {
            let find_res = self.invoke("findCards", serde_json::json!({"query": format!("\"deck:{}\"", name)})).await?;
            let ids: Vec<i64> = serde_json::from_value(find_res).unwrap_or_default();
            
            // Now query IF there are LC tagged cards in this deck
            let lc_find_res = self.invoke("findCards", serde_json::json!({"query": format!("\"deck:{}\" tag:LC_Version*", name)})).await?;
            let lc_ids: Vec<i64> = serde_json::from_value(lc_find_res).unwrap_or_default();

            decks.push(DeckInfo {
                deck_id: did.to_string(),
                name,
                card_count: ids.len(),
                new_count: 0,
                learning_count: 0,
                review_count: 0,
                is_lc: !lc_ids.is_empty(),
            });
        }
        
        decks.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(decks)
    }

    async fn save_deck(&self, deck: &NewDeckData) -> Result<usize, Box<dyn std::error::Error + Send + Sync>> {
        // 1. Ensure the Panglot note model exists
        let model_names: Vec<String> = serde_json::from_value(
            self.invoke("modelNames", serde_json::json!({})).await?
        )?;
        if !model_names.iter().any(|n| n == MODEL_NAME) {
            println!("  [save_deck] Creating '{}' note model in Anki", MODEL_NAME);
            self.invoke("createModel", serde_json::json!({
                "modelName": MODEL_NAME,
                "inOrderFields": MODEL_FIELDS,
                "css": MODEL_CSS,
                "cardTemplates": [{
                    "Name": "Card 1",
                    "Front": MODEL_QFMT,
                    "Back": MODEL_AFMT,
                }]
            })).await?;
        } else {
            // Model exists — ensure all fields are present
            let existing_fields: Vec<String> = serde_json::from_value(
                self.invoke("modelFieldNames", serde_json::json!({"modelName": MODEL_NAME})).await?
            )?;
            for &field in MODEL_FIELDS {
                if !existing_fields.iter().any(|f| f == field) {
                    println!("  [save_deck] Adding missing field '{}' to model", field);
                    self.invoke("modelFieldAdd", serde_json::json!({
                        "modelName": MODEL_NAME,
                        "fieldName": field,
                    })).await?;
                }
            }

            // Update styling and templates to match current code
            println!("  [save_deck] Updating '{}' model styling & templates", MODEL_NAME);
            self.invoke("updateModelStyling", serde_json::json!({
                "model": {
                    "name": MODEL_NAME,
                    "css": MODEL_CSS,
                }
            })).await?;
            self.invoke("updateModelTemplates", serde_json::json!({
                "model": {
                    "name": MODEL_NAME,
                    "templates": {
                        "Card 1": {
                            "Front": MODEL_QFMT,
                            "Back": MODEL_AFMT,
                        }
                    }
                }
            })).await?;
        }

        // 2. Create deck (idempotent)
        self.invoke("createDeck", serde_json::json!({"deck": &deck.name})).await?;

        // 3. Store audio media files & build notes
        let version_tag = format!("LC_Version:{}", env!("CARGO_PKG_VERSION"));
        let mut notes = Vec::with_capacity(deck.cards.len());

        for entry in &deck.cards {
            // Store audio if present
            let audio_val = if let Some(audio_path) = &entry.audio_path {
                let file_path = Path::new(audio_path);
                let filename = file_path
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("audio.mp3")
                    .to_string();

                if file_path.exists() {
                    println!("  [save_deck] Storing media '{}'", filename);
                    self.invoke("storeMediaFile", serde_json::json!({
                        "filename": &filename,
                        "path": audio_path,
                    })).await?;
                } else {
                    eprintln!("  [save_deck] WARNING: Audio file not found at '{}' — skipping", audio_path);
                }
                format!("[sound:{}]", filename)
            } else {
                String::new()
            };

            notes.push(serde_json::json!({
                "deckName": &deck.name,
                "modelName": MODEL_NAME,
                "fields": {
                    "Front": &entry.front_html,
                    "Back": &entry.back_html,
                    "SkillName": &entry.skill_name,
                    "IPA": &entry.ipa,
                    "Audio": &audio_val,
                    "Explanation": &entry.explanation,
                    "Metadata": &entry.metadata_json,
                },
                "tags": [&version_tag],
                "options": {
                    "allowDuplicate": false,
                    "duplicateScope": "deck",
                }
            }));
        }

        // 4. Add all notes in one batch
        let result = self.invoke("addNotes", serde_json::json!({"notes": notes})).await?;
        let note_ids: Vec<serde_json::Value> = serde_json::from_value(result)?;

        let mut added = 0;
        let mut updated = 0;

        for (i, note_id) in note_ids.iter().enumerate() {
            if !note_id.is_null() {
                added += 1;
            } else {
                // Duplicate — find the existing note and update its fields
                let entry = &deck.cards[i];
                let find_result = self.invoke("findNotes", serde_json::json!({
                    "query": format!("\"deck:{}\" \"Front:{}\"",
                        &deck.name,
                        entry.front_html.replace('"', "\\\""))
                })).await?;
                let existing_ids: Vec<i64> = serde_json::from_value(find_result).unwrap_or_default();

                if let Some(&nid) = existing_ids.first() {
                    let audio_val = entry.audio_path.as_deref()
                        .map(|p| {
                            let filename = Path::new(p)
                                .file_name()
                                .and_then(|n| n.to_str())
                                .unwrap_or("audio.mp3");
                            format!("[sound:{}]", filename)
                        })
                        .unwrap_or_default();

                    self.invoke("updateNoteFields", serde_json::json!({
                        "note": {
                            "id": nid,
                            "fields": {
                                "Front": &entry.front_html,
                                "Back": &entry.back_html,
                                "SkillName": &entry.skill_name,
                                "IPA": &entry.ipa,
                                "Audio": &audio_val,
                                "Explanation": &entry.explanation,
                                "Metadata": &entry.metadata_json,
                            }
                        }
                    })).await?;
                    updated += 1;
                }
            }
        }

        println!("  [save_deck] '{}': {} added, {} updated", deck.name, added, updated);
        Ok(added + updated)
    }
}

// ----- Tests -----

#[cfg(test)]
mod tests {
    use super::*;

    // Mock implementation for testing
    struct MockAnkiStorageProvider {
        cards: Vec<StoredCard>,
    }

    #[async_trait::async_trait]
    impl StorageProvider for MockAnkiStorageProvider {
        async fn fetch_cards(&self) -> Result<Vec<StoredCard>, Box<dyn std::error::Error + Send + Sync>> {
            Ok(self.cards.clone())
        }

        async fn fetch_decks(&self) -> Result<Vec<DeckInfo>, Box<dyn std::error::Error + Send + Sync>> {
            Ok(vec![
                DeckInfo { deck_id: "1".to_string(), name: "Polish::Grammar".to_string(), card_count: 42, new_count: 0, learning_count: 0, review_count: 0, is_lc: true },
                DeckInfo { deck_id: "2".to_string(), name: "Polish::Vocabulary".to_string(), card_count: 128, new_count: 0, learning_count: 0, review_count: 0, is_lc: false },
            ])
        }

        async fn save_deck(&self, _deck: &NewDeckData) -> Result<usize, Box<dyn std::error::Error + Send + Sync>> {
            Ok(0)
        }
    }

    fn sample_cards() -> Vec<StoredCard> {
        vec![
            StoredCard {
                note_id: "1".to_string(),
                card_id: "100".to_string(),
                fields: "front\x1fback".to_string(),
                tags: "grammar polish".to_string(),
                interval_days: 30.0,
                lapses: 0,
            },
            StoredCard {
                note_id: "2".to_string(),
                card_id: "101".to_string(),
                fields: "front2\x1fback2".to_string(),
                tags: "leech vocabulary".to_string(),
                interval_days: 5.0,
                lapses: 8,
            },
            StoredCard {
                note_id: "3".to_string(),
                card_id: "102".to_string(),
                fields: "front3\x1fback3".to_string(),
                tags: "".to_string(),
                interval_days: 0.0,
                lapses: 0,
            },
        ]
    }

    #[tokio::test]
    async fn mock_repository_returns_cards() {
        let repo = MockAnkiStorageProvider {
            cards: sample_cards(),
        };
        let cards = repo.fetch_cards().await.unwrap();
        assert_eq!(cards.len(), 3);
    }

    #[test]
    fn card_is_mature() {
        let cards = sample_cards();
        assert!(cards[0].is_mature());   // interval=30 >= 21
        assert!(!cards[1].is_mature());  // interval=5 < 21
        assert!(!cards[2].is_mature());  // interval=0 < 21
    }

    #[test]
    fn card_is_leech() {
        let cards = sample_cards();
        assert!(!cards[0].is_leech());  // tags="grammar polish"
        assert!(cards[1].is_leech());   // tags="leech vocabulary"
        assert!(!cards[2].is_leech());  // tags=""
    }

    #[test]
    fn raw_anki_card_serialization_roundtrip() {
        let card = &sample_cards()[0];
        let json = serde_json::to_string(card).unwrap();
        let deserialized: StoredCard = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.note_id, card.note_id);
        assert_eq!(deserialized.card_id, card.card_id);
        assert_eq!(deserialized.fields, card.fields);
    }

    #[tokio::test]
    async fn mock_repository_returns_decks() {
        let repo = MockAnkiStorageProvider {
            cards: vec![],
        };
        let decks = repo.fetch_decks().await.unwrap();
        assert_eq!(decks.len(), 2);
        assert_eq!(decks[0].name, "Polish::Grammar");
        assert_eq!(decks[0].card_count, 42);
        assert_eq!(decks[1].name, "Polish::Vocabulary");
        assert_eq!(decks[1].card_count, 128);
    }
}

