use lc_core::storage::{DeckInfo, NewDeckData, StorageProvider, StoredCard};

// ----- AnkiConnect Implementation -----

/// Storage backend implementation using AnkiConnect.
pub struct AnkiStorageProvider {
    url: String,
    client: reqwest::Client,
}

impl AnkiStorageProvider {
    pub fn new(url: impl Into<String>) -> Self {
        Self {
            url: url.into(),
            client: reqwest::Client::new(),
        }
    }

    async fn invoke(
        &self,
        action: &str,
        params: serde_json::Value,
    ) -> Result<serde_json::Value, Box<dyn std::error::Error + Send + Sync>> {
        let payload = serde_json::json!({
            "action": action,
            "version": 6,
            "params": params
        });

        let mut retries = 0;
        let max_retries = 4;
        let mut delay = tokio::time::Duration::from_millis(50);

        loop {
            if retries == 0 {
                tokio::time::sleep(tokio::time::Duration::from_millis(15)).await;
            }

            match self
                .client
                .post(&self.url)
                .header("Connection", "close")
                .json(&payload)
                .send()
                .await
            {
                Ok(resp) => {
                    if !resp.status().is_success() {
                        return Err(format!("AnkiConnect returned HTTP {}", resp.status()).into());
                    }

                    let body: serde_json::Value = resp.json().await?;
                    if let Some(err) = body.get("error") {
                        if !err.is_null() {
                            return Err(format!("AnkiConnect error: {}", err).into());
                        }
                    }

                    return Ok(body["result"].clone());
                }
                Err(e) => {
                    if retries >= max_retries {
                        return Err(Box::new(e));
                    }
                    tracing::warn!(retry = retries + 1, max_retries, delay_ms = delay.as_millis() as u64, %e, "AnkiConnect network error");
                    tokio::time::sleep(delay).await;
                    retries += 1;
                    delay *= 2; // exponential backoff
                }
            }
        }
    }
}

#[async_trait::async_trait]
impl StorageProvider for AnkiStorageProvider {
    async fn fetch_cards(
        &self,
    ) -> Result<Vec<StoredCard>, Box<dyn std::error::Error + Send + Sync>> {
        // Find ONLY cards generated by Panglot
        let find_result = self
            .invoke("findCards", serde_json::json!({"query": "tag:LC_Version*"}))
            .await?;
        let card_ids: Vec<i64> = serde_json::from_value(find_result)?;

        if card_ids.is_empty() {
            return Ok(vec![]);
        }

        let cards_info_result = self
            .invoke("cardsInfo", serde_json::json!({"cards": card_ids}))
            .await?;
        let cards_info: Vec<serde_json::Value> = serde_json::from_value(cards_info_result)?;

        let mut raw_cards = Vec::with_capacity(cards_info.len());
        for info in cards_info {
            let card_id = info["cardId"].as_i64().unwrap_or(0);
            let note_id = info["note"].as_i64().unwrap_or(0);
            let interval_days = info["interval"].as_i64().unwrap_or(0) as f64;
            let lapses = info["lapses"].as_i64().unwrap_or(0) as i32;

            // Reconstruct fields separated by \x1f (which Analyzer expects)
            let mut fields_string = String::new();
            if let Some(fields_obj) = info["fields"].as_object() {
                let mut ordered_fields = Vec::new();
                for (_k, v) in fields_obj {
                    let order = v["order"].as_i64().unwrap_or(0);
                    let val_str = v["value"].as_str().unwrap_or("");
                    ordered_fields.push((order, val_str));
                }
                ordered_fields.sort_by_key(|a| a.0);

                let vals: Vec<&str> = ordered_fields.into_iter().map(|f| f.1).collect();
                fields_string = vals.join("\x1f");
            }

            let tags = if let Some(tags_arr) = info["tags"].as_array() {
                tags_arr
                    .iter()
                    .filter_map(|t| t.as_str())
                    .collect::<Vec<_>>()
                    .join(" ")
            } else {
                "".to_string()
            };

            raw_cards.push(StoredCard {
                note_id: note_id.to_string(),
                card_id: card_id.to_string(),
                fields: fields_string,
                tags,
                interval_days,
                lapses,
            });
        }

        Ok(raw_cards)
    }

    async fn fetch_decks(&self) -> Result<Vec<DeckInfo>, Box<dyn std::error::Error + Send + Sync>> {
        Ok(Vec::new())
    }

    async fn save_deck(
        &self,
        _deck: &NewDeckData,
    ) -> Result<usize, Box<dyn std::error::Error + Send + Sync>> {
        Err("AnkiStorageProvider is read-only; Panglot no longer exports decks to Anki".into())
    }

    async fn delete_deck(
        &self,
        _deck_id: &str,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Err("AnkiStorageProvider is read-only; Panglot no longer deletes Anki decks".into())
    }
}

// ----- Tests -----

#[cfg(test)]
mod tests {
    use super::*;

    // Mock implementation for testing
    struct MockAnkiStorageProvider {
        cards: Vec<StoredCard>,
    }

    #[async_trait::async_trait]
    impl StorageProvider for MockAnkiStorageProvider {
        async fn fetch_cards(
            &self,
        ) -> Result<Vec<StoredCard>, Box<dyn std::error::Error + Send + Sync>> {
            Ok(self.cards.clone())
        }

        async fn fetch_decks(
            &self,
        ) -> Result<Vec<DeckInfo>, Box<dyn std::error::Error + Send + Sync>> {
            Ok(vec![
                DeckInfo {
                    deck_id: "1".to_string(),
                    name: "Polish::Grammar".to_string(),
                    target_language: "pol".to_string(),
                    card_count: 42,
                    new_count: 0,
                    learning_count: 0,
                    review_count: 0,
                    is_lc: true,
                },
                DeckInfo {
                    deck_id: "2".to_string(),
                    name: "Polish::Vocabulary".to_string(),
                    target_language: "pol".to_string(),
                    card_count: 128,
                    new_count: 0,
                    learning_count: 0,
                    review_count: 0,
                    is_lc: false,
                },
            ])
        }

        async fn save_deck(
            &self,
            _deck: &NewDeckData,
        ) -> Result<usize, Box<dyn std::error::Error + Send + Sync>> {
            Ok(0)
        }

        async fn delete_deck(
            &self,
            _deck_id: &str,
        ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
            Ok(())
        }
    }

    fn sample_cards() -> Vec<StoredCard> {
        vec![
            StoredCard {
                note_id: "1".to_string(),
                card_id: "100".to_string(),
                fields: "front\x1fback".to_string(),
                tags: "grammar polish".to_string(),
                interval_days: 30.0,
                lapses: 0,
            },
            StoredCard {
                note_id: "2".to_string(),
                card_id: "101".to_string(),
                fields: "front2\x1fback2".to_string(),
                tags: "leech vocabulary".to_string(),
                interval_days: 5.0,
                lapses: 8,
            },
            StoredCard {
                note_id: "3".to_string(),
                card_id: "102".to_string(),
                fields: "front3\x1fback3".to_string(),
                tags: "".to_string(),
                interval_days: 0.0,
                lapses: 0,
            },
        ]
    }

    #[tokio::test]
    async fn mock_repository_returns_cards() {
        let repo = MockAnkiStorageProvider {
            cards: sample_cards(),
        };
        let cards = repo.fetch_cards().await.unwrap();
        assert_eq!(cards.len(), 3);
    }

    #[test]
    fn card_is_mature() {
        let cards = sample_cards();
        assert!(cards[0].is_mature()); // interval=30 >= 21
        assert!(!cards[1].is_mature()); // interval=5 < 21
        assert!(!cards[2].is_mature()); // interval=0 < 21
    }

    #[test]
    fn card_is_leech() {
        let cards = sample_cards();
        assert!(!cards[0].is_leech()); // tags="grammar polish"
        assert!(cards[1].is_leech()); // tags="leech vocabulary"
        assert!(!cards[2].is_leech()); // tags=""
    }

    #[test]
    fn raw_anki_card_serialization_roundtrip() {
        let card = &sample_cards()[0];
        let json = serde_json::to_string(card).unwrap();
        let deserialized: StoredCard = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.note_id, card.note_id);
        assert_eq!(deserialized.card_id, card.card_id);
        assert_eq!(deserialized.fields, card.fields);
    }

    #[tokio::test]
    async fn mock_repository_returns_decks() {
        let repo = MockAnkiStorageProvider { cards: vec![] };
        let decks = repo.fetch_decks().await.unwrap();
        assert_eq!(decks.len(), 2);
        assert_eq!(decks[0].name, "Polish::Grammar");
        assert_eq!(decks[0].card_count, 42);
        assert_eq!(decks[1].name, "Polish::Vocabulary");
        assert_eq!(decks[1].card_count, 128);
    }
}
